// <auto-generated />
namespace DeprtEntity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Linkedbetweendepartmentandmanager : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Linkedbetweendepartmentandmanager));
        
        string IMigrationMetadata.Id
        {
            get { return "202310200924156_Linked between department and manager"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
